### PR TITLE
Add Linux Serial Support

### PR DESCRIPTION
**Pull request by linoshkmalayil**
# Linux Serial Support
**What is working:**
- [x] Opening and closing the specified device
- [x] Reading from specified device
- [x] Writing to specified device
- [x] Reading and writing to emulator using double buffer to improve performance

## Explanation on Double Buffer
read() and write() operations on IO devices are slow due to wait delays.
So to prevent the emulator from slowing down while serial IO operations are being  performed, they have been moved to a separate thread with independent buffer and allow the emulator to copy and write to it's buffer from the independent buffer.

### CODE REVIEW

**Comment by mckuhei** [comment]
I think you can use select() or poll() to check the serial interface status to decide whether to perform IO operations.

**Comment by linoshkmalayil** [comment]
> I think you can use select() or poll() to check the serial interface status to decide whether to perform IO operations.

Tried poll() still no improvement
select() usage is heavily discouraged, plus is it much slower than poll()
Also as far as I have read about read() and write(), they do have some form of polling in them.

**Comment by linoshkmalayil** [comment]
Currently implemented a thread independent, unsafe IO operation which allows the emulator to run at full speed. Not a huge fan of this but works.

**Comment by mckuhei** [comment]
Maybe you could create a new thread in Linux to read into a temporary buffer and copy to the read buffer later.

**Comment by linoshkmalayil** [comment]
> Maybe you could create a new thread in Linux to read into a temporary buffer and copy to the read buffer later.

Little tricky, not exactly sure where to call such a function while emulator is running...
Because emulator at some point must create this thread and close it.

**Comment by mckuhei** [comment]
Can be created at the end of SERIAL_Init() and closed at the beginning of SERIAL_Close()

**Comment by linoshkmalayil** [comment]
> Can be created at the end of SERIAL_Init() and closed at the beginning of SERIAL_Close()

Oh right...
I totally forgot about it...
I'll check it out and update

**Comment by mckuhei** [comment]
By the way, you can test whether the serial interface is working by connecting it to the SC-55mkII. If the SC-55mkII receives MIDI messages at the same time when using the serial interface, it will transmit the MIDI messages to the computer through the serial interface. If two SC-55mkIIs are connected together through the serial interface, if one SC-55mkII receives a message, the other SC-55mkII will respond.

**Comment by mckuhei** [comment]
I just had success driving my Yamaha MU2000 through a Nuked SC-55, but my SC-88 Pro doesn't seem to like my USB serial port :(

**Comment by mckuhei** [comment]
Moreover, there are some problems with the MIDI input of the current version. Some MIDI input data will be discarded, which will not happen in previous versions. I am currently investigating this problem.

**Comment by linoshkmalayil** [comment]
> By the way, you can test whether the serial interface is working by connecting it to the SC-55mkII. If the SC-55mkII receives MIDI messages at the same time when using the serial interface, it will transmit the MIDI messages to the computer through the serial interface. If two SC-55mkIIs are connected together through the serial interface, if one SC-55mkII receives a message, the other SC-55mkII will respond.

I had fully tested it virtually.
On Linux using `socat`, you can create dummy serial port pairs. 
I connected Nuked SC-55 to one of them and from the terminal sent SysEx bytes to the other one, which worked successfully.
Tried transmitting a MIDI file from the terminal, but since the terminal literally dumps bytes into the serial interface, the emulator played the file garbled. But when I logged the data being received, it is receiving the MIDI file correctly, just not in playable state.

**Comment by linoshkmalayil** [comment]
> I just had success driving my Yamaha MU2000 through a Nuked SC-55, but my SC-88 Pro doesn't seem to like my USB serial port :(

Usually serial interface issues occur when the baudrate is high, I am not sure on how USB to serial conversion changes things.
Also the serial ports are a less used feature in these modules. (Even now MIDI is the better way to connect these units)
So issues that occur using serial port connection on modern systems maybe unknown.

**Comment by mckuhei** [comment]
> > I just had success driving my Yamaha MU2000 through a Nuked SC-55, but my SC-88 Pro doesn't seem to like my USB serial port :(
> 
> Usually serial interface issues occur when the baudrate is high, I am not sure on how USB to serial conversion changes things. Also the serial ports are a less used feature in these modules. (Even now MIDI is the better way to connect these units) So issues that occur using serial port connection on modern systems maybe unknown.

But I didn't transmit any data. I'm sure TX is always at a high level. It may be because I didn't connect RTS/CTS.

**Comment by linoshkmalayil** [comment]
I have updated to use independent buffer on another thread, this works so far.

**Comment by mckuhei** [comment]
Good job, It also support unix?

**Comment by mckuhei** [comment]
If not, re add dummy driver for unix

**Comment by linoshkmalayil** [comment]
> Good job, It also support unix?

Yes, all the headers and functions used are POSIX compliant, hence will compile on BSD, Linux, Mac and other Unix based OS.
I have updated and rebased commits.
Also I have used filename serial_posix.c and used UNIX condition in CMake to indicate that it's POSIX compliant.

**Pull request merged**
